export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS";
export const ADD_TO_SHOPPING_CART="ADD_TO_SHOPPING_CART";
export const SUB_TO_SHOPPING_CART="SUB_TO_SHOPPING_CART";
export const DELETE_ALL_SHOPPING_CART="DELETE_ALL_SHOPPING_CART";
export const GET_PRODUCTS_INFO="GET_PRODUCTS_INFO"
